title: Griffith lab of Ecology, Evolution, and Change
description: Daniel M. Griffith, Ph.D.
email: griffith.dan@gmail.com

twitter_username: griffithdan
github_username: griffithdan
researchgate_username: Daniel_Griffith2
googlescholar_username: 8SlmK_sAAAAJ&hl

markdown: kramdown
