title: Griffith lab of<br> Ecology,\ Evolution, and\ Change
description: Research at the nexus of biogeography, evolutionary biology, and global change.
email: griffith.dan@gmail.com

twitter_username: griffithdan
github_username: griffithdan
researchgate_username: Daniel_Griffith2
googlescholar_username: 8SlmK_sAAAAJ&hl

markdown: kramdown
