title: Griffith lab of<br> Ecology,<br> Evolution, and<br> Change
description: Bridging ecophysiology, evolutionary biology, biogeography, and change.
email: griffith.dan@gmail.com

twitter_username: griffithdan
github_username: griffithdan
researchgate_username: Daniel_Griffith2
googlescholar_username: 8SlmK_sAAAAJ&hl

markdown: kramdown
