title: Savanna and grassland biogeography
description: Daniel M. Griffith, Ph.D.
email: griffith.dan@gmail.com

twitter_username: griffithdan
github_username: griffithdan
researchgate_username: Daniel_Griffith2

markdown: kramdown
